### ISSUE TITLE
Page 65: "The first parameter" -> "The third parameter"

### ISSUE THREAD

**Issue by alanxoc3** [AllenDowney/ThinkOS#16]
You said **first** when you meant **third**, talking about the parameters to "**pthread_create**".

BTW, great book! I was very impressed. It did a great job at explaining some low level concepts to me.

**Comment by AllenDowney** [comment]
Fixed https://github.com/AllenDowney/ThinkOS/commit/d0edd0e36d1c7b0a38de002e1462f492f5dcb997

Thank you!
