### ISSUE TITLE
Typo in size of virtual address space

### ISSUE THREAD

**Issue by sthiago** [AllenDowney/ThinkOS#33]
"On a 64-bit system, the size of the virtual address space is 2^64 bytes, or 4 * 1024^6 bytes." should read "[...] 2^64 bytes, or 2^4 * 1024^6 bytes."

https://github.com/AllenDowney/ThinkOS/blob/master/book/book.tex#L1118

**Comment by AllenDowney** [comment]
Fixed.  Thanks!
