### ISSUE TITLE
latex compile: the hevea.sty missing

### ISSUE THREAD

**Issue by wenbindu** [AllenDowney/ThinkOS#36]
When I compile the book.tex in texstudio with xelatex.exe command. 
I got an error: hevea.sty missing.
And, I copy it from the ThinkPython repository, it worked.
Maybe, the file should be appended in this repository

**Comment by AllenDowney** [comment]
Yes, thanks for letting me know.

You could also delete the usepackage{hevea} line. You would only need it to generate HTML.
