### ISSUE TITLE
Small grammatical change

### ISSUE THREAD

**Issue by forlornborg** [AllenDowney/ThinkOS#6]
page 47:
"If the data **<that>** the CPU needs is usually in cache, the program can run
at the ...

**Comment by AllenDowney** [comment]
Are you objecting to data as a singular noun, or the clumsiness of "the data the CPU needs"?

**Comment by forlornborg** [comment]
Apologies for the ambiguity; I was commenting on the second. "If the data that the CPU needs..."

**Comment by AllenDowney** [comment]
I went with "If the data needed by the CPU are usually in cache"

Thanks for the suggestion!
